apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: cluster-group-lcm.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Common is the Schema for the commons API
      displayName: Common
      kind: Common
      name: commons.ran.openshift.io
      version: v1alpha1
    - description: Group is the Schema for the groups API
      displayName: Group
      kind: Group
      name: groups.ran.openshift.io
      version: v1alpha1
    - description: Site is the Schema for the sites API
      displayName: Site
      kind: Site
      name: sites.ran.openshift.io
      version: v1alpha1
  description: Cluster Group LCM operator allows you to manage software lifecycle of groups of clusters
  displayName: cluster-group-lcm
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - acm
  - multicluster
  - software lifecycle management
  - lcm
  links:
  - name: Cluster Group Lcm
    url: https://cluster-group-lcm.domain
  maturity: alpha
  provider:
    name: Red Hat
    url: redhat.com
  version: 0.0.0
