apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test
  namespace: default
spec:
  clusters:
  - sno
  managedPolicies:
  - upgrade
  remediationStrategy:
    maxConcurrency: 1
  enable: false
